### ISSUE TITLE
lanedet-main/configs/condlane/resnet50_culane.py

### ISSUE THREAD

**Issue by FANG-MING** [Turoad/lanedet#22]
when i use the config "lanedet-main/configs/condlane/resnet50_culane.py",but got
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 35, in main
    runner.train()
  File "/home/data6/fmsfms/lanedet-main/lanedet/engine/runner.py", line 94, in train
    self.train_epoch(epoch, train_loader)
  File "/home/data6/fmsfms/lanedet-main/lanedet/engine/runner.py", line 67, in train_epoch
    output = self.net(data)
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data6/fmsfms/lanedet-main/lanedet/models/nets/detector.py", line 26, in forward
    fea[-1] = self.aggregator(fea[-1])
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data6/fmsfms/lanedet-main/lanedet/models/aggregators/transformer.py", line 152, in forward
    src = layer(src, pos.to(src.device))
  File "/home/data6/fms/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data6/fmsfms/lanedet-main/lanedet/models/aggregators/transformer.py", line 106, in forward
    x += pos
RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 0

**Comment by Turoad** [comment]
Currently, Condlane need change `batch_size=1` for inference.
