### ISSUE TITLE
RuntimeError: The detected CUDA version (10.1) mismatches the version that was used to compile PyTorch (11.3). Please make sure to use the same CUDA versions.

### ISSUE THREAD

**Issue by tensorturtle** [Turoad/lanedet#29]
Hello, thank you for this code. I followed the directions carefully, but I can't get it to work.

When I run:
```
python setup.py build develop
```

I get:
```
RuntimeError:
The detected CUDA version (10.1) mismatches the version that was used to compile
PyTorch (11.3). Please make sure to use the same CUDA versions.
```

I have tried installing older (cuda 10.1-era) pytorch and torchvision, but that did nothing.
```
conda remove pytorch torchvision cudatoolkit
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1.168 -c pytorch
```

Do I have to downgrade CUDA in my whole computer? Is there no way to make it work inside conda?

Hope to hear from you.
Thank you

**Comment by keoghka** [comment]
Along the same lines as the question above. With RTX 3000 series cards, they don't support CUDA 10.X and would need CUDA 11. Is it possible to make this project work with CUDA 11? Would it be a significant amount of work?

**Comment by gautamjain1009** [comment]
@tensorturtle I faced the same issue, try installing pytorch in the conda env. via pip like 
'pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
'
I ran the scripts too they run fine.

**Comment by Turoad** [comment]
Thanks @gautamjain1009.

**Comment by qm-intel** [comment]
@gautamjain1009 your solution works. But after all installation when I am trying to import the packages, I get the following error:

`
>>> import torch
>>> from torch_geometric.data import Data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch_sparse/__init__.py", line 41, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch/jit/_script.py", line 1128, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch/jit/_script.py", line 138, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
object has no attribute sparse_csr_tensor:
  File "/home/es/anaconda3/envs/bio-env/lib/python3.7/site-packages/torch_sparse/tensor.py", line 511
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
    
return torch.sparse_csr_tensor(rowptr, col, value, self.sizes())
 ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>>> a = torch.randn(3, 4).to_sparse_csr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tensor' object has no attribute 'to_sparse_csr'
`

**Comment by GoregoriDes** [comment]
Check if you have the 11.3 version installed (which you should have), go to edit the path in the environment variables and set the path for cuda to the right version (if you have multiple versions, they all should be listed in there)
![image](https://github.com/Turoad/lanedet/assets/118157090/7b133592-3953-40c1-8aa2-e43fe9397dac)
