### ISSUE TITLE
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

### ISSUE THREAD

**Issue by farouk09** [Turoad/lanedet#38]
Hi,

I'm trying to run inference on Jetson TX2 with this command _**" _python3 tools/detect.py configs/resa/resa34_culane.py --img images/ --load_from resa_r34_culane.pth --savedir ./vis_ "**_ and i'm getting this error, Can anyone tell me what's the problem please !

> Traceback (most recent call last):
  File "tools/detect.py", line 8, in <module>
    from lanedet.datasets.process import Process
  File "/home/hellojetsontx2/lanedet/lanedet/datasets/__init__.py", line 3, in <module>
    from .tusimple import TuSimple
  File "/home/hellojetsontx2/lanedet/lanedet/datasets/tusimple.py", line 7, in <module>
    from .base_dataset import BaseDataset
  File "/home/hellojetsontx2/lanedet/lanedet/datasets/base_dataset.py", line 10, in <module>
    from .process import Process
  File "/home/hellojetsontx2/lanedet/lanedet/datasets/process/__init__.py", line 7, in <module>
    from .collect_lane import CollectLane
  File "/home/hellojetsontx2/lanedet/lanedet/datasets/process/collect_lane.py", line 9, in <module>
    from shapely.geometry import Polygon, Point, LineString
  File "/home/hellojetsontx2/.local/lib/python3.6/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/hellojetsontx2/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/hellojetsontx2/.local/lib/python3.6/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/home/hellojetsontx2/.local/lib/python3.6/site-packages/shapely/geos.py", line 99, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/home/hellojetsontx2/.local/lib/python3.6/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

**Comment by Turoad** [comment]
It seems you don't have the library `libgeos_c.so`.  You might try this: https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants.

Or

`collect_lane.py` this file is used in `CondlaneNet`. If you don't need testing it, you can try to comment this line(https://github.com/Turoad/lanedet/blob/main/lanedet/datasets/process/__init__.py#L7):
```
from .collect_lane import CollectLane
```
