### ISSUE TITLE
KeyError: 'img_metas'

### ISSUE THREAD

**Issue by 514398473** [Turoad/lanedet#40]
Hello!
This commit https://github.com/Turoad/lanedet/commit/d36ba736d0b30574563e4e7b39e86516cb75b1c5 can fix this issue.
the latest code has included the above submission. This prompt still appears when running culane

Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 35, in main
    runner.train()
  File "/data4/xuzheng/lanedet/lanedet/engine/runner.py", line 94, in train
    self.train_epoch(epoch, train_loader)
  File "/data4/xuzheng/lanedet/lanedet/engine/runner.py", line 67, in train_epoch
    output = self.net(data)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data4/xuzheng/lanedet/lanedet/models/nets/detector.py", line 32, in forward
    out = self.heads(fea, batch=batch)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data4/xuzheng/lanedet/lanedet/models/heads/condlane.py", line 1012, in forward
    return self.forward_train(x_list, kwargs['batch'])
  File "/data4/xuzheng/lanedet/lanedet/models/heads/condlane.py", line 868, in forward_train
    img_metas = batch['img_metas']
KeyError: 'img_metas'

**Comment by 514398473** [comment]
Using configs/condlane/resnet101_culane.py

**Comment by Turoad** [comment]
Thanks. It's fixed by this commit: 95c06c2c5e73ef1a666fb5596e69e2d61af79b83.

**Comment by 514398473** [comment]
Thank you. You have successfully started training.
