### ISSUE TITLE
cannot import name 'nms_impl' from partially initialized module 'lanedet.ops'

### ISSUE THREAD

**Issue by minhoooo1** [Turoad/lanedet#46]
when i run main.py 
The following errors are reported:

Traceback (most recent call last):
  File "C:/Users/MINHOO/Desktop/大三下比赛/lanedet-main/main.py", line 8, in <module>
    from lanedet.utils.config import Config
  File "C:\Users\MINHOO\Desktop\大三下比赛\lanedet-main\lanedet\__init__.py", line 1, in <module>
    from .ops import *
  File "C:\Users\MINHOO\Desktop\大三下比赛\lanedet-main\lanedet\ops\__init__.py", line 1, in <module>
    from .nms import nms
  File "C:\Users\MINHOO\Desktop\大三下比赛\lanedet-main\lanedet\ops\nms.py", line 29, in <module>
    from . import nms_impl
ImportError: cannot import name 'nms_impl' from partially initialized module 'lanedet.ops' (most likely due to a circular import) (C:\Users\MINHOO\Desktop\大三下比赛\lanedet-main\lanedet\ops\__init__.py)

Process finished with exit code 1

**Comment by Turoad** [comment]
Refer this issue: https://github.com/Turoad/lanedet/issues/3.
Please read the existing issue before raising new issue.

**Comment by minhoooo1** [comment]
All right Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 中午1:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Turoad/lanedet] cannot import name &#39;nms_impl&#39; from partially initialized module &#39;lanedet.ops&#39; (Issue #46)





 
Refer this issue: #3.
 Please read the existing issue before raising new issue.
