### ISSUE TITLE
About KeyError in the training of CondaLaneNet

### ISSUE THREAD

**Issue by Cinderstones** [Turoad/lanedet#47]
Traceback (most recent call last):
  File "/home/room/python_projects/lanedet-main/main.py", line 65, in <module>
    main()
  File "/home/room/python_projects/lanedet-main/main.py", line 35, in main
    runner.train()
  File "/home/room/python_projects/lanedet-main/lanedet/engine/runner.py", line 94, in train
    self.train_epoch(epoch, train_loader)
  File "/home/room/python_projects/lanedet-main/lanedet/engine/runner.py", line 67, in train_epoch
    output = self.net(data)
  File "/home/room/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/room/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/room/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/room/python_projects/lanedet-main/lanedet/models/nets/detector.py", line 32, in forward
    out = self.heads(fea, batch=batch)
  File "/home/room/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/room/python_projects/lanedet-main/lanedet/models/heads/condlane.py", line 1011, in forward
    return self.forward_train(x_list, kwargs['batch'])
  File "/home/room/python_projects/lanedet-main/lanedet/models/heads/condlane.py", line 867, in forward_train
    img_metas = batch['img_metas']
KeyError: 'img_metas'

**Comment by Turoad** [comment]
Are you using the latest code? 
It is fixed. Refer this issue: https://github.com/Turoad/lanedet/issues/40.

**Comment by Cinderstones** [comment]
Thanks a lot. I download the latest version and the Error is fixed!
