### ISSUE TITLE
Inference code 'LineStringsOnImage' object has no attribute 'clip_out_of_image_'

### ISSUE THREAD

**Issue by TriaSirax** [Turoad/lanedet#7]
Hi, first of all thanks for everything, great work!

I have a problem running the inference code:

`python tools/detect.py configs/laneatt/resnet18_culane.py --img ./05081544_0305-005400.jpg --load_from laneatt_r18_culane.pth --savedir ./test`

pretrained model:  https://download.pytorch.org/models/resnet18-5c106cde.pth  
Traceback (most recent call last):  
  File "tools/detect.py", line 84, in <module>  
    process(args)  
  File "tools/detect.py", line 73, in process  
    detect.run(p)
  File "tools/detect.py", line 47, in run
    data = self.preprocess(data)
  File "tools/detect.py", line 29, in preprocess
    data = self.processes(data)
  File "/content/gdrive/My Drive/Staj/lanedet/lanedet/lanedet/datasets/process/process.py", line 35, in __call__
    data = t(data)
  File "/content/gdrive/My Drive/Staj/lanedet/lanedet/lanedet/datasets/process/generate_lane_line.py", line 132, in __call__
    line_strings.clip_out_of_image_()
AttributeError: 'LineStringsOnImage' object has no attribute 'clip_out_of_image_'

At first  I got the error on this issue: #6 . Than I modify the code as you suggested and now I'm getting this AttributeError. I'm working on google colab if that's relevant.

Thank you.

**Comment by TriaSirax** [comment]
Just now I tried inferencing resa and it works fine, looks like problem is about laneatt.

**Comment by Turoad** [comment]
What's the version of your imgaug? I'm using 0.4.0.

**Comment by TriaSirax** [comment]
Yeah, it was 0.2.9 now I upgraded it to 0.4.0 and it works. Thanks.
