### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\L00653~1\\AppData\\Local\\Temp\\tmphpklern8\\tmpkydalnxp.py'

### ISSUE THREAD

**Issue by Sober-xz** [Turoad/lanedet#70]
Traceback (most recent call last):
  File "tools/detect.py", line 86, in <module>
    process(args)
  File "tools/detect.py", line 68, in process
    cfg = Config.fromfile(args.config)
  File "d:\lanedet\lanedet\utils\config.py", line 180, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "d:\lanedet\lanedet\utils\config.py", line 105, in _file2dict
    shutil.copyfile(filename,
  File "C:\Users\l00653465\Anaconda3\envs\lanedet\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\L00653~1\\AppData\\Local\\Temp\\tmphpklern8\\tmpkydalnxp.py'

在进行训练和测试的时候都会报这个错

**Comment by xqh5201314** [comment]
你好，你解决这个问题了吗？

**Comment by cxuucx** [comment]
我也出现这个错误了，搜了下各种回答都是权限问题，设置了也没用啊，不知道是不是windows系统太多bug的问题？？

**Comment by xqh5201314** [comment]
> 我也出现这个错误了，搜了下各种回答都是权限问题，设置了也没用啊，不知道是不是windows系统太多bug的问题？？

用ubuntu就可以了，windows应该解决不了这个问题

**Comment by cxuucx** [comment]
> > 我也出现这个错误了，搜了下各种回答都是权限问题，设置了也没用啊，不知道是不是windows系统太多bug的问题？？
> 
> 用ubuntu就可以了，windows应该解决不了这个问题

我试试吧，还从没用过这个
